# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui',
# licensing of 'control.ui' applies.
#
# Created: Wed Jul 10 11:13:18 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Control(object):
    def setupUi(self, Control):
        Control.setObjectName("Control")
        Control.resize(1024, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Control.sizePolicy().hasHeightForWidth())
        Control.setSizePolicy(sizePolicy)
        Control.setMinimumSize(QtCore.QSize(1024, 500))
        Control.setMaximumSize(QtCore.QSize(1024, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Control.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Control)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.minutes_layout = QtWidgets.QHBoxLayout()
        self.minutes_layout.setObjectName("minutes_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.minutes_layout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.minutes_layout.addWidget(self.label)
        self.loadLogoButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadLogoButton.setObjectName("loadLogoButton")
        self.minutes_layout.addWidget(self.loadLogoButton)
        self.division_label = QtWidgets.QLabel(self.centralwidget)
        self.division_label.setObjectName("division_label")
        self.minutes_layout.addWidget(self.division_label)
        self.division_combobox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.division_combobox.sizePolicy().hasHeightForWidth())
        self.division_combobox.setSizePolicy(sizePolicy)
        self.division_combobox.setObjectName("division_combobox")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.division_combobox.addItem("")
        self.minutes_layout.addWidget(self.division_combobox)
        self.buzzer_label = QtWidgets.QLabel(self.centralwidget)
        self.buzzer_label.setObjectName("buzzer_label")
        self.minutes_layout.addWidget(self.buzzer_label)
        self.sound_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.sound_combobox.setObjectName("sound_combobox")
        self.minutes_layout.addWidget(self.sound_combobox)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.soundOnRadioButton = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.soundOnRadioButton.sizePolicy().hasHeightForWidth())
        self.soundOnRadioButton.setSizePolicy(sizePolicy)
        self.soundOnRadioButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/soundon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundOnRadioButton.setIcon(icon1)
        self.soundOnRadioButton.setChecked(True)
        self.soundOnRadioButton.setObjectName("soundOnRadioButton")
        self.horizontalLayout.addWidget(self.soundOnRadioButton)
        self.soundOffRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.soundOffRadioButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/soundoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundOffRadioButton.setIcon(icon2)
        self.soundOffRadioButton.setObjectName("soundOffRadioButton")
        self.horizontalLayout.addWidget(self.soundOffRadioButton)
        self.minutes_layout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.minutes_layout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.minutes_layout)
        self.comp_pts_labels_hlayout = QtWidgets.QHBoxLayout()
        self.comp_pts_labels_hlayout.setObjectName("comp_pts_labels_hlayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 14pt;")
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.comp_pts_labels_hlayout.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("font: 14pt;")
        self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.comp_pts_labels_hlayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("font: 14pt;")
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.comp_pts_labels_hlayout.addWidget(self.label_8)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.comp_pts_labels_hlayout.addItem(spacerItem2)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setStyleSheet("font: 14pt;")
        self.label_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.comp_pts_labels_hlayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setStyleSheet("font: 14pt;")
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.comp_pts_labels_hlayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setStyleSheet("font: 14pt;")
        self.label_13.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.comp_pts_labels_hlayout.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.comp_pts_labels_hlayout)
        self.competitor_scores_layout = QtWidgets.QHBoxLayout()
        self.competitor_scores_layout.setObjectName("competitor_scores_layout")
        self.comp1_pts_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_pts_label.sizePolicy().hasHeightForWidth())
        self.comp1_pts_label.setSizePolicy(sizePolicy)
        self.comp1_pts_label.setStyleSheet("background-color: rgb(60, 125, 60);\n"
"color: \'white\';\n"
"font: 48pt;\n"
"")
        self.comp1_pts_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_pts_label.setObjectName("comp1_pts_label")
        self.competitor_scores_layout.addWidget(self.comp1_pts_label)
        self.comp1_adv_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_adv_label.sizePolicy().hasHeightForWidth())
        self.comp1_adv_label.setSizePolicy(sizePolicy)
        self.comp1_adv_label.setStyleSheet("font: 49pt;\n"
"background-color: rgb(225, 225, 0);\n"
"color: \'white\';")
        self.comp1_adv_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_adv_label.setObjectName("comp1_adv_label")
        self.competitor_scores_layout.addWidget(self.comp1_adv_label)
        self.comp1_pen_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_pen_label.sizePolicy().hasHeightForWidth())
        self.comp1_pen_label.setSizePolicy(sizePolicy)
        self.comp1_pen_label.setStyleSheet("font: 48pt;\n"
"background-color: rgb(200,0,0);\n"
"color: \'white\';")
        self.comp1_pen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_pen_label.setObjectName("comp1_pen_label")
        self.competitor_scores_layout.addWidget(self.comp1_pen_label)
        spacerItem3 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.competitor_scores_layout.addItem(spacerItem3)
        self.comp2_pts_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_pts_label.sizePolicy().hasHeightForWidth())
        self.comp2_pts_label.setSizePolicy(sizePolicy)
        self.comp2_pts_label.setStyleSheet("background-color: rgb(60, 125, 60);\n"
"color: \'white\';\n"
"font:  48pt;\n"
"")
        self.comp2_pts_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_pts_label.setObjectName("comp2_pts_label")
        self.competitor_scores_layout.addWidget(self.comp2_pts_label)
        self.comp2_adv_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_adv_label.sizePolicy().hasHeightForWidth())
        self.comp2_adv_label.setSizePolicy(sizePolicy)
        self.comp2_adv_label.setStyleSheet("font: 49pt;\n"
"background-color: rgb(225, 225, 0);\n"
"color: \'white\';")
        self.comp2_adv_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_adv_label.setObjectName("comp2_adv_label")
        self.competitor_scores_layout.addWidget(self.comp2_adv_label)
        self.comp2_pen_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_pen_label.sizePolicy().hasHeightForWidth())
        self.comp2_pen_label.setSizePolicy(sizePolicy)
        self.comp2_pen_label.setStyleSheet("font: 48pt;\n"
"background-color: rgb(200,0,0);\n"
"color: \'white\';")
        self.comp2_pen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_pen_label.setObjectName("comp2_pen_label")
        self.competitor_scores_layout.addWidget(self.comp2_pen_label)
        self.verticalLayout.addLayout(self.competitor_scores_layout)
        self.comp_names_hlayout = QtWidgets.QHBoxLayout()
        self.comp_names_hlayout.setObjectName("comp_names_hlayout")
        self.comp1_name_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_name_label.sizePolicy().hasHeightForWidth())
        self.comp1_name_label.setSizePolicy(sizePolicy)
        self.comp1_name_label.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.comp1_name_label.setFont(font)
        self.comp1_name_label.setStyleSheet("font: 24pt;\n"
"background-color: rgb(0, 0, 200);\n"
"color: \'white\';")
        self.comp1_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_name_label.setObjectName("comp1_name_label")
        self.comp_names_hlayout.addWidget(self.comp1_name_label)
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.comp_names_hlayout.addItem(spacerItem4)
        self.comp2_name_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_name_label.sizePolicy().hasHeightForWidth())
        self.comp2_name_label.setSizePolicy(sizePolicy)
        self.comp2_name_label.setMaximumSize(QtCore.QSize(500, 16777215))
        self.comp2_name_label.setStyleSheet("font: 24pt;\n"
"background-color: \'white\';")
        self.comp2_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_name_label.setObjectName("comp2_name_label")
        self.comp_names_hlayout.addWidget(self.comp2_name_label)
        self.verticalLayout.addLayout(self.comp_names_hlayout)
        self.names_timer_hlayout = QtWidgets.QHBoxLayout()
        self.names_timer_hlayout.setObjectName("names_timer_hlayout")
        self.comp1_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comp1_lineedit.sizePolicy().hasHeightForWidth())
        self.comp1_lineedit.setSizePolicy(sizePolicy)
        self.comp1_lineedit.setMinimumSize(QtCore.QSize(50, 0))
        self.comp1_lineedit.setMaxLength(50)
        self.comp1_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_lineedit.setClearButtonEnabled(True)
        self.comp1_lineedit.setObjectName("comp1_lineedit")
        self.names_timer_hlayout.addWidget(self.comp1_lineedit)
        self.comp1_flag_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.comp1_flag_combobox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comp1_flag_combobox.setCurrentText("")
        self.comp1_flag_combobox.setIconSize(QtCore.QSize(32, 16))
        self.comp1_flag_combobox.setObjectName("comp1_flag_combobox")
        self.names_timer_hlayout.addWidget(self.comp1_flag_combobox)
        self.p1_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.p1_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p1_pushButton.setObjectName("p1_pushButton")
        self.names_timer_hlayout.addWidget(self.p1_pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.names_timer_hlayout.addItem(spacerItem5)
        self.timer_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.timer_label.sizePolicy().hasHeightForWidth())
        self.timer_label.setSizePolicy(sizePolicy)
        self.timer_label.setStyleSheet("font: 48pt \'Consolas\';\n"
"")
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.names_timer_hlayout.addWidget(self.timer_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.names_timer_hlayout.addItem(spacerItem6)
        self.comp2_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_lineedit.sizePolicy().hasHeightForWidth())
        self.comp2_lineedit.setSizePolicy(sizePolicy)
        self.comp2_lineedit.setMinimumSize(QtCore.QSize(50, 0))
        self.comp2_lineedit.setMaxLength(50)
        self.comp2_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_lineedit.setClearButtonEnabled(True)
        self.comp2_lineedit.setObjectName("comp2_lineedit")
        self.names_timer_hlayout.addWidget(self.comp2_lineedit)
        self.comp2_flag_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.comp2_flag_combobox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comp2_flag_combobox.setIconSize(QtCore.QSize(32, 16))
        self.comp2_flag_combobox.setObjectName("comp2_flag_combobox")
        self.names_timer_hlayout.addWidget(self.comp2_flag_combobox)
        self.p2_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.p2_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p2_pushButton.setCheckable(False)
        self.p2_pushButton.setObjectName("p2_pushButton")
        self.names_timer_hlayout.addWidget(self.p2_pushButton)
        self.verticalLayout.addLayout(self.names_timer_hlayout)
        self.add_score_layout = QtWidgets.QHBoxLayout()
        self.add_score_layout.setObjectName("add_score_layout")
        self.comp1_add2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_add2.sizePolicy().hasHeightForWidth())
        self.comp1_add2.setSizePolicy(sizePolicy)
        self.comp1_add2.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: \'white\';")
        self.comp1_add2.setObjectName("comp1_add2")
        self.add_score_layout.addWidget(self.comp1_add2)
        self.comp1_add3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_add3.sizePolicy().hasHeightForWidth())
        self.comp1_add3.setSizePolicy(sizePolicy)
        self.comp1_add3.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);\n"
"")
        self.comp1_add3.setObjectName("comp1_add3")
        self.add_score_layout.addWidget(self.comp1_add3)
        self.comp1_add4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_add4.sizePolicy().hasHeightForWidth())
        self.comp1_add4.setSizePolicy(sizePolicy)
        self.comp1_add4.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_add4.setObjectName("comp1_add4")
        self.add_score_layout.addWidget(self.comp1_add4)
        self.comp1_addA = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_addA.sizePolicy().hasHeightForWidth())
        self.comp1_addA.setSizePolicy(sizePolicy)
        self.comp1_addA.setStyleSheet("background: rgb(255, 255, 130);\n"
"font: 20pt \'Arial\';\n"
"")
        self.comp1_addA.setObjectName("comp1_addA")
        self.add_score_layout.addWidget(self.comp1_addA)
        self.comp1_addP = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_addP.sizePolicy().hasHeightForWidth())
        self.comp1_addP.setSizePolicy(sizePolicy)
        self.comp1_addP.setStyleSheet("background:rgb(200, 0, 0);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_addP.setObjectName("comp1_addP")
        self.add_score_layout.addWidget(self.comp1_addP)
        self.play_pause_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.play_pause_button.sizePolicy().hasHeightForWidth())
        self.play_pause_button.setSizePolicy(sizePolicy)
        self.play_pause_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause_button.setIcon(icon3)
        self.play_pause_button.setIconSize(QtCore.QSize(32, 32))
        self.play_pause_button.setObjectName("play_pause_button")
        self.add_score_layout.addWidget(self.play_pause_button)
        self.comp2_add2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_add2.sizePolicy().hasHeightForWidth())
        self.comp2_add2.setSizePolicy(sizePolicy)
        self.comp2_add2.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_add2.setObjectName("comp2_add2")
        self.add_score_layout.addWidget(self.comp2_add2)
        self.comp2_add3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_add3.sizePolicy().hasHeightForWidth())
        self.comp2_add3.setSizePolicy(sizePolicy)
        self.comp2_add3.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_add3.setObjectName("comp2_add3")
        self.add_score_layout.addWidget(self.comp2_add3)
        self.comp2_add4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_add4.sizePolicy().hasHeightForWidth())
        self.comp2_add4.setSizePolicy(sizePolicy)
        self.comp2_add4.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_add4.setObjectName("comp2_add4")
        self.add_score_layout.addWidget(self.comp2_add4)
        self.comp2_addA = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_addA.sizePolicy().hasHeightForWidth())
        self.comp2_addA.setSizePolicy(sizePolicy)
        self.comp2_addA.setStyleSheet("background: rgb(255, 255, 130);\n"
"font: 20pt \'Arial\';\n"
"")
        self.comp2_addA.setObjectName("comp2_addA")
        self.add_score_layout.addWidget(self.comp2_addA)
        self.comp2_addP = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_addP.sizePolicy().hasHeightForWidth())
        self.comp2_addP.setSizePolicy(sizePolicy)
        self.comp2_addP.setStyleSheet("background:rgb(200, 0, 0);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_addP.setObjectName("comp2_addP")
        self.add_score_layout.addWidget(self.comp2_addP)
        self.verticalLayout.addLayout(self.add_score_layout)
        self.del_score_layout = QtWidgets.QHBoxLayout()
        self.del_score_layout.setObjectName("del_score_layout")
        self.comp1_del2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_del2.sizePolicy().hasHeightForWidth())
        self.comp1_del2.setSizePolicy(sizePolicy)
        self.comp1_del2.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);\n"
"")
        self.comp1_del2.setObjectName("comp1_del2")
        self.del_score_layout.addWidget(self.comp1_del2)
        self.comp1_del3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_del3.sizePolicy().hasHeightForWidth())
        self.comp1_del3.setSizePolicy(sizePolicy)
        self.comp1_del3.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_del3.setObjectName("comp1_del3")
        self.del_score_layout.addWidget(self.comp1_del3)
        self.comp1_del4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_del4.sizePolicy().hasHeightForWidth())
        self.comp1_del4.setSizePolicy(sizePolicy)
        self.comp1_del4.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_del4.setObjectName("comp1_del4")
        self.del_score_layout.addWidget(self.comp1_del4)
        self.comp1_delA = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_delA.sizePolicy().hasHeightForWidth())
        self.comp1_delA.setSizePolicy(sizePolicy)
        self.comp1_delA.setStyleSheet("background: rgb(255, 255, 130);\n"
"font: 20pt \'Arial\';\n"
"")
        self.comp1_delA.setObjectName("comp1_delA")
        self.del_score_layout.addWidget(self.comp1_delA)
        self.comp1_delP = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_delP.sizePolicy().hasHeightForWidth())
        self.comp1_delP.setSizePolicy(sizePolicy)
        self.comp1_delP.setStyleSheet("background:rgb(200, 0, 0);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_delP.setObjectName("comp1_delP")
        self.del_score_layout.addWidget(self.comp1_delP)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon4)
        self.stop_button.setIconSize(QtCore.QSize(32, 32))
        self.stop_button.setObjectName("stop_button")
        self.del_score_layout.addWidget(self.stop_button)
        self.comp2_del2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_del2.sizePolicy().hasHeightForWidth())
        self.comp2_del2.setSizePolicy(sizePolicy)
        self.comp2_del2.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_del2.setObjectName("comp2_del2")
        self.del_score_layout.addWidget(self.comp2_del2)
        self.comp2_del3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_del3.sizePolicy().hasHeightForWidth())
        self.comp2_del3.setSizePolicy(sizePolicy)
        self.comp2_del3.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_del3.setObjectName("comp2_del3")
        self.del_score_layout.addWidget(self.comp2_del3)
        self.comp2_del4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_del4.sizePolicy().hasHeightForWidth())
        self.comp2_del4.setSizePolicy(sizePolicy)
        self.comp2_del4.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_del4.setObjectName("comp2_del4")
        self.del_score_layout.addWidget(self.comp2_del4)
        self.comp2_delA = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_delA.sizePolicy().hasHeightForWidth())
        self.comp2_delA.setSizePolicy(sizePolicy)
        self.comp2_delA.setStyleSheet("background: rgb(255, 255, 130);\n"
"font: 20pt \'Arial\';\n"
"")
        self.comp2_delA.setObjectName("comp2_delA")
        self.del_score_layout.addWidget(self.comp2_delA)
        self.comp2_delP = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_delP.sizePolicy().hasHeightForWidth())
        self.comp2_delP.setSizePolicy(sizePolicy)
        self.comp2_delP.setStyleSheet("background:rgb(200, 0, 0);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_delP.setObjectName("comp2_delP")
        self.del_score_layout.addWidget(self.comp2_delP)
        self.verticalLayout.addLayout(self.del_score_layout)
        Control.setCentralWidget(self.centralwidget)

        self.retranslateUi(Control)
        self.division_combobox.setCurrentIndex(14)
        self.comp2_flag_combobox.setCurrentIndex(-1)
        QtCore.QObject.connect(self.comp1_lineedit, QtCore.SIGNAL("textChanged(QString)"), self.comp1_name_label.setText)
        QtCore.QObject.connect(self.comp2_lineedit, QtCore.SIGNAL("textChanged(QString)"), self.comp2_name_label.setText)
        QtCore.QMetaObject.connectSlotsByName(Control)

    def retranslateUi(self, Control):
        Control.setWindowTitle(QtWidgets.QApplication.translate("Control", "Openroll", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Control", "Load Logo:", None, -1))
        self.loadLogoButton.setText(QtWidgets.QApplication.translate("Control", "...", None, -1))
        self.division_label.setText(QtWidgets.QApplication.translate("Control", "Division: ", None, -1))
        self.division_combobox.setCurrentText(QtWidgets.QApplication.translate("Control", "AGE 18-29 - ADULT - WHITE", None, -1))
        self.division_combobox.setItemText(0, QtWidgets.QApplication.translate("Control", "AGE 4 - MIGHTY MITE 1 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(1, QtWidgets.QApplication.translate("Control", "AGE 5 - MIGHTY MITE 2 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(2, QtWidgets.QApplication.translate("Control", "AGE 6 - MIGHTY MITE 3 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(3, QtWidgets.QApplication.translate("Control", "AGE 7 - PEE WEE 1 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(4, QtWidgets.QApplication.translate("Control", "AGE 8 - PEE WEE 2 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(5, QtWidgets.QApplication.translate("Control", "AGE 9 - PEE WEE 3 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(6, QtWidgets.QApplication.translate("Control", "AGE 10 - JUNIOR 1 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(7, QtWidgets.QApplication.translate("Control", "AGE 11 - JUNIOR 2 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(8, QtWidgets.QApplication.translate("Control", "AGE 12 - JUNIOR 3 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(9, QtWidgets.QApplication.translate("Control", "AGE 13 - TEEN 1 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(10, QtWidgets.QApplication.translate("Control", "AGE 14 - TEEN 2 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(11, QtWidgets.QApplication.translate("Control", "AGE 15 - TEEN 3 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(12, QtWidgets.QApplication.translate("Control", "AGE 16 - JUVENILE 1 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(13, QtWidgets.QApplication.translate("Control", "AGE 17 - JUVENILE 2 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(14, QtWidgets.QApplication.translate("Control", "AGE 18-29 - ADULT - WHITE", None, -1))
        self.division_combobox.setItemText(15, QtWidgets.QApplication.translate("Control", "AGE 18-29 - ADULT - BLUE", None, -1))
        self.division_combobox.setItemText(16, QtWidgets.QApplication.translate("Control", "AGE 18-29 - ADULT - PURPLE", None, -1))
        self.division_combobox.setItemText(17, QtWidgets.QApplication.translate("Control", "AGE 18-29 - ADULT - BROWN", None, -1))
        self.division_combobox.setItemText(18, QtWidgets.QApplication.translate("Control", "AGE 18-29 - ADULT - BLACK", None, -1))
        self.division_combobox.setItemText(19, QtWidgets.QApplication.translate("Control", "AGE 30-34 - MASTER 1 - WHITE", None, -1))
        self.division_combobox.setItemText(20, QtWidgets.QApplication.translate("Control", "AGE 30-35 - MASTER 1 - BLUE", None, -1))
        self.division_combobox.setItemText(21, QtWidgets.QApplication.translate("Control", "AGE 30-35 - MASTER 1 - PURPLE", None, -1))
        self.division_combobox.setItemText(22, QtWidgets.QApplication.translate("Control", "AGE 30-35 - MASTER 1 - BROWN", None, -1))
        self.division_combobox.setItemText(23, QtWidgets.QApplication.translate("Control", "AGE 30-35 - MASTER 1 - BLACK", None, -1))
        self.division_combobox.setItemText(24, QtWidgets.QApplication.translate("Control", "AGE 36-40 - MASTER 2 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(25, QtWidgets.QApplication.translate("Control", "AGE 41-45 - MASTER 3 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(26, QtWidgets.QApplication.translate("Control", "AGE 46-50 - MASTER 4 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(27, QtWidgets.QApplication.translate("Control", "AGE 51-55 - MASTER 5 - ALL BELTS", None, -1))
        self.division_combobox.setItemText(28, QtWidgets.QApplication.translate("Control", "AGE 56+       MASTER 6 - ALL BELTS", None, -1))
        self.buzzer_label.setText(QtWidgets.QApplication.translate("Control", "Buzzer Sound:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Control", "Points", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Control", "Advantages", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Control", "Penalties", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Control", "Points", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Control", "Advantages", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Control", "Penalties", None, -1))
        self.comp1_pts_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp1_adv_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp1_pen_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp2_pts_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp2_adv_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp2_pen_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp1_name_label.setText(QtWidgets.QApplication.translate("Control", "Competitor A", None, -1))
        self.comp2_name_label.setText(QtWidgets.QApplication.translate("Control", "Competitor B", None, -1))
        self.comp1_lineedit.setText(QtWidgets.QApplication.translate("Control", "Competitor A", None, -1))
        self.p1_pushButton.setText(QtWidgets.QApplication.translate("Control", "...", None, -1))
        self.timer_label.setText(QtWidgets.QApplication.translate("Control", "5:00", None, -1))
        self.comp2_lineedit.setText(QtWidgets.QApplication.translate("Control", "Competitor B", None, -1))
        self.p2_pushButton.setText(QtWidgets.QApplication.translate("Control", "...", None, -1))
        self.comp1_add2.setText(QtWidgets.QApplication.translate("Control", "+2", None, -1))
        self.comp1_add3.setText(QtWidgets.QApplication.translate("Control", "+3", None, -1))
        self.comp1_add4.setText(QtWidgets.QApplication.translate("Control", "+4", None, -1))
        self.comp1_addA.setText(QtWidgets.QApplication.translate("Control", "+A", None, -1))
        self.comp1_addP.setText(QtWidgets.QApplication.translate("Control", "+P", None, -1))
        self.comp2_add2.setText(QtWidgets.QApplication.translate("Control", "+2", None, -1))
        self.comp2_add3.setText(QtWidgets.QApplication.translate("Control", "+3", None, -1))
        self.comp2_add4.setText(QtWidgets.QApplication.translate("Control", "+4", None, -1))
        self.comp2_addA.setText(QtWidgets.QApplication.translate("Control", "+A", None, -1))
        self.comp2_addP.setText(QtWidgets.QApplication.translate("Control", "+P", None, -1))
        self.comp1_del2.setText(QtWidgets.QApplication.translate("Control", "-2", None, -1))
        self.comp1_del3.setText(QtWidgets.QApplication.translate("Control", "-3", None, -1))
        self.comp1_del4.setText(QtWidgets.QApplication.translate("Control", "-4", None, -1))
        self.comp1_delA.setText(QtWidgets.QApplication.translate("Control", "-A", None, -1))
        self.comp1_delP.setText(QtWidgets.QApplication.translate("Control", "-P", None, -1))
        self.comp2_del2.setText(QtWidgets.QApplication.translate("Control", "-2", None, -1))
        self.comp2_del3.setText(QtWidgets.QApplication.translate("Control", "-3", None, -1))
        self.comp2_del4.setText(QtWidgets.QApplication.translate("Control", "-4", None, -1))
        self.comp2_delA.setText(QtWidgets.QApplication.translate("Control", "-A", None, -1))
        self.comp2_delP.setText(QtWidgets.QApplication.translate("Control", "-P", None, -1))

import openroll_rc
