# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui',
# licensing of 'control.ui' applies.
#
# Created: Fri Jul 19 14:15:31 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Control(object):
    def setupUi(self, Control):
        Control.setObjectName("Control")
        Control.resize(1024, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Control.sizePolicy().hasHeightForWidth())
        Control.setSizePolicy(sizePolicy)
        Control.setMinimumSize(QtCore.QSize(1024, 500))
        Control.setMaximumSize(QtCore.QSize(1024, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Control.setWindowIcon(icon)
        self.central_widget = QtWidgets.QWidget(Control)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.minutes_layout = QtWidgets.QHBoxLayout()
        self.minutes_layout.setObjectName("minutes_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.minutes_layout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setObjectName("label")
        self.minutes_layout.addWidget(self.label)
        self.load_logo_button = QtWidgets.QPushButton(self.central_widget)
        self.load_logo_button.setObjectName("load_logo_button")
        self.minutes_layout.addWidget(self.load_logo_button)
        self.division_label = QtWidgets.QLabel(self.central_widget)
        self.division_label.setObjectName("division_label")
        self.minutes_layout.addWidget(self.division_label)
        self.division_combobox = QtWidgets.QComboBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.division_combobox.sizePolicy().hasHeightForWidth())
        self.division_combobox.setSizePolicy(sizePolicy)
        self.division_combobox.setCurrentText("")
        self.division_combobox.setObjectName("division_combobox")
        self.minutes_layout.addWidget(self.division_combobox)
        self.buzzer_label = QtWidgets.QLabel(self.central_widget)
        self.buzzer_label.setObjectName("buzzer_label")
        self.minutes_layout.addWidget(self.buzzer_label)
        self.sound_combobox = QtWidgets.QComboBox(self.central_widget)
        self.sound_combobox.setObjectName("sound_combobox")
        self.minutes_layout.addWidget(self.sound_combobox)
        self.group_box = QtWidgets.QGroupBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.group_box.sizePolicy().hasHeightForWidth())
        self.group_box.setSizePolicy(sizePolicy)
        self.group_box.setTitle("")
        self.group_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.group_box.setFlat(False)
        self.group_box.setObjectName("group_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.group_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sound_on_radio_button = QtWidgets.QRadioButton(self.group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sound_on_radio_button.sizePolicy().hasHeightForWidth())
        self.sound_on_radio_button.setSizePolicy(sizePolicy)
        self.sound_on_radio_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/soundon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_on_radio_button.setIcon(icon1)
        self.sound_on_radio_button.setChecked(True)
        self.sound_on_radio_button.setObjectName("sound_on_radio_button")
        self.horizontalLayout.addWidget(self.sound_on_radio_button)
        self.sound_off_radio_button = QtWidgets.QRadioButton(self.group_box)
        self.sound_off_radio_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/soundoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_off_radio_button.setIcon(icon2)
        self.sound_off_radio_button.setObjectName("sound_off_radio_button")
        self.horizontalLayout.addWidget(self.sound_off_radio_button)
        self.minutes_layout.addWidget(self.group_box)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.minutes_layout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.minutes_layout)
        self.comp_pts_labels_hlayout = QtWidgets.QHBoxLayout()
        self.comp_pts_labels_hlayout.setObjectName("comp_pts_labels_hlayout")
        self.label_2 = QtWidgets.QLabel(self.central_widget)
        self.label_2.setStyleSheet("font: 14pt;")
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.comp_pts_labels_hlayout.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.central_widget)
        self.label_9.setStyleSheet("font: 14pt;")
        self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.comp_pts_labels_hlayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.central_widget)
        self.label_8.setStyleSheet("font: 14pt;")
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.comp_pts_labels_hlayout.addWidget(self.label_8)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.comp_pts_labels_hlayout.addItem(spacerItem2)
        self.label_11 = QtWidgets.QLabel(self.central_widget)
        self.label_11.setStyleSheet("font: 14pt;")
        self.label_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.comp_pts_labels_hlayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.central_widget)
        self.label_12.setStyleSheet("font: 14pt;")
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.comp_pts_labels_hlayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.central_widget)
        self.label_13.setStyleSheet("font: 14pt;")
        self.label_13.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.comp_pts_labels_hlayout.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.comp_pts_labels_hlayout)
        self.competitor_scores_layout = QtWidgets.QHBoxLayout()
        self.competitor_scores_layout.setObjectName("competitor_scores_layout")
        self.comp1_pts_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_pts_label.sizePolicy().hasHeightForWidth())
        self.comp1_pts_label.setSizePolicy(sizePolicy)
        self.comp1_pts_label.setStyleSheet("background-color: rgb(60, 125, 60);\n"
"color: \'white\';\n"
"font: 48pt;\n"
"")
        self.comp1_pts_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_pts_label.setObjectName("comp1_pts_label")
        self.competitor_scores_layout.addWidget(self.comp1_pts_label)
        self.comp1_adv_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_adv_label.sizePolicy().hasHeightForWidth())
        self.comp1_adv_label.setSizePolicy(sizePolicy)
        self.comp1_adv_label.setStyleSheet("font: 49pt;\n"
"background-color: rgb(225, 225, 0);\n"
"color: \'white\';")
        self.comp1_adv_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_adv_label.setObjectName("comp1_adv_label")
        self.competitor_scores_layout.addWidget(self.comp1_adv_label)
        self.comp1_pen_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_pen_label.sizePolicy().hasHeightForWidth())
        self.comp1_pen_label.setSizePolicy(sizePolicy)
        self.comp1_pen_label.setStyleSheet("font: 48pt;\n"
"background-color: rgb(200,0,0);\n"
"color: \'white\';")
        self.comp1_pen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_pen_label.setObjectName("comp1_pen_label")
        self.competitor_scores_layout.addWidget(self.comp1_pen_label)
        spacerItem3 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.competitor_scores_layout.addItem(spacerItem3)
        self.comp2_pts_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_pts_label.sizePolicy().hasHeightForWidth())
        self.comp2_pts_label.setSizePolicy(sizePolicy)
        self.comp2_pts_label.setStyleSheet("background-color: rgb(60, 125, 60);\n"
"color: \'white\';\n"
"font:  48pt;\n"
"")
        self.comp2_pts_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_pts_label.setObjectName("comp2_pts_label")
        self.competitor_scores_layout.addWidget(self.comp2_pts_label)
        self.comp2_adv_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_adv_label.sizePolicy().hasHeightForWidth())
        self.comp2_adv_label.setSizePolicy(sizePolicy)
        self.comp2_adv_label.setStyleSheet("font: 49pt;\n"
"background-color: rgb(225, 225, 0);\n"
"color: \'white\';")
        self.comp2_adv_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_adv_label.setObjectName("comp2_adv_label")
        self.competitor_scores_layout.addWidget(self.comp2_adv_label)
        self.comp2_pen_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_pen_label.sizePolicy().hasHeightForWidth())
        self.comp2_pen_label.setSizePolicy(sizePolicy)
        self.comp2_pen_label.setStyleSheet("font: 48pt;\n"
"background-color: rgb(200,0,0);\n"
"color: \'white\';")
        self.comp2_pen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_pen_label.setObjectName("comp2_pen_label")
        self.competitor_scores_layout.addWidget(self.comp2_pen_label)
        self.verticalLayout.addLayout(self.competitor_scores_layout)
        self.comp_names_hlayout = QtWidgets.QHBoxLayout()
        self.comp_names_hlayout.setObjectName("comp_names_hlayout")
        self.comp1_name_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_name_label.sizePolicy().hasHeightForWidth())
        self.comp1_name_label.setSizePolicy(sizePolicy)
        self.comp1_name_label.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.comp1_name_label.setFont(font)
        self.comp1_name_label.setStyleSheet("font: 24pt;\n"
"background-color: rgb(0, 0, 200);\n"
"color: \'white\';")
        self.comp1_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_name_label.setObjectName("comp1_name_label")
        self.comp_names_hlayout.addWidget(self.comp1_name_label)
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.comp_names_hlayout.addItem(spacerItem4)
        self.comp2_name_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_name_label.sizePolicy().hasHeightForWidth())
        self.comp2_name_label.setSizePolicy(sizePolicy)
        self.comp2_name_label.setMaximumSize(QtCore.QSize(500, 16777215))
        self.comp2_name_label.setStyleSheet("font: 24pt;\n"
"background-color: \'white\';")
        self.comp2_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_name_label.setObjectName("comp2_name_label")
        self.comp_names_hlayout.addWidget(self.comp2_name_label)
        self.verticalLayout.addLayout(self.comp_names_hlayout)
        self.names_timer_hlayout = QtWidgets.QHBoxLayout()
        self.names_timer_hlayout.setObjectName("names_timer_hlayout")
        self.comp1_lineedit = QtWidgets.QLineEdit(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comp1_lineedit.sizePolicy().hasHeightForWidth())
        self.comp1_lineedit.setSizePolicy(sizePolicy)
        self.comp1_lineedit.setMinimumSize(QtCore.QSize(50, 0))
        self.comp1_lineedit.setMaxLength(50)
        self.comp1_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_lineedit.setClearButtonEnabled(True)
        self.comp1_lineedit.setObjectName("comp1_lineedit")
        self.names_timer_hlayout.addWidget(self.comp1_lineedit)
        self.comp1_flag_combobox = QtWidgets.QComboBox(self.central_widget)
        self.comp1_flag_combobox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comp1_flag_combobox.setCurrentText("")
        self.comp1_flag_combobox.setIconSize(QtCore.QSize(32, 16))
        self.comp1_flag_combobox.setObjectName("comp1_flag_combobox")
        self.names_timer_hlayout.addWidget(self.comp1_flag_combobox)
        self.p1_push_button = QtWidgets.QPushButton(self.central_widget)
        self.p1_push_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p1_push_button.setObjectName("p1_push_button")
        self.names_timer_hlayout.addWidget(self.p1_push_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.names_timer_hlayout.addItem(spacerItem5)
        self.timer_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.timer_label.sizePolicy().hasHeightForWidth())
        self.timer_label.setSizePolicy(sizePolicy)
        self.timer_label.setStyleSheet("font: 48pt \'Consolas\';\n"
"")
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.names_timer_hlayout.addWidget(self.timer_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.names_timer_hlayout.addItem(spacerItem6)
        self.comp2_lineedit = QtWidgets.QLineEdit(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_lineedit.sizePolicy().hasHeightForWidth())
        self.comp2_lineedit.setSizePolicy(sizePolicy)
        self.comp2_lineedit.setMinimumSize(QtCore.QSize(50, 0))
        self.comp2_lineedit.setMaxLength(50)
        self.comp2_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_lineedit.setClearButtonEnabled(True)
        self.comp2_lineedit.setObjectName("comp2_lineedit")
        self.names_timer_hlayout.addWidget(self.comp2_lineedit)
        self.comp2_flag_combobox = QtWidgets.QComboBox(self.central_widget)
        self.comp2_flag_combobox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comp2_flag_combobox.setIconSize(QtCore.QSize(32, 16))
        self.comp2_flag_combobox.setObjectName("comp2_flag_combobox")
        self.names_timer_hlayout.addWidget(self.comp2_flag_combobox)
        self.p2_push_button = QtWidgets.QPushButton(self.central_widget)
        self.p2_push_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p2_push_button.setCheckable(False)
        self.p2_push_button.setObjectName("p2_push_button")
        self.names_timer_hlayout.addWidget(self.p2_push_button)
        self.verticalLayout.addLayout(self.names_timer_hlayout)
        self.add_score_layout = QtWidgets.QHBoxLayout()
        self.add_score_layout.setObjectName("add_score_layout")
        self.comp1_add_2 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_add_2.sizePolicy().hasHeightForWidth())
        self.comp1_add_2.setSizePolicy(sizePolicy)
        self.comp1_add_2.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: \'white\';")
        self.comp1_add_2.setObjectName("comp1_add_2")
        self.add_score_layout.addWidget(self.comp1_add_2)
        self.comp1_add_3 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_add_3.sizePolicy().hasHeightForWidth())
        self.comp1_add_3.setSizePolicy(sizePolicy)
        self.comp1_add_3.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);\n"
"")
        self.comp1_add_3.setObjectName("comp1_add_3")
        self.add_score_layout.addWidget(self.comp1_add_3)
        self.comp1_add_4 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_add_4.sizePolicy().hasHeightForWidth())
        self.comp1_add_4.setSizePolicy(sizePolicy)
        self.comp1_add_4.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_add_4.setObjectName("comp1_add_4")
        self.add_score_layout.addWidget(self.comp1_add_4)
        self.comp1_add_a = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_add_a.sizePolicy().hasHeightForWidth())
        self.comp1_add_a.setSizePolicy(sizePolicy)
        self.comp1_add_a.setStyleSheet("background: rgb(255, 255, 130);\n"
"font: 20pt \'Arial\';\n"
"")
        self.comp1_add_a.setObjectName("comp1_add_a")
        self.add_score_layout.addWidget(self.comp1_add_a)
        self.comp1_add_p = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_add_p.sizePolicy().hasHeightForWidth())
        self.comp1_add_p.setSizePolicy(sizePolicy)
        self.comp1_add_p.setStyleSheet("background:rgb(200, 0, 0);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_add_p.setObjectName("comp1_add_p")
        self.add_score_layout.addWidget(self.comp1_add_p)
        self.play_pause_button = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.play_pause_button.sizePolicy().hasHeightForWidth())
        self.play_pause_button.setSizePolicy(sizePolicy)
        self.play_pause_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause_button.setIcon(icon3)
        self.play_pause_button.setIconSize(QtCore.QSize(32, 32))
        self.play_pause_button.setObjectName("play_pause_button")
        self.add_score_layout.addWidget(self.play_pause_button)
        self.comp2_add_2 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_add_2.sizePolicy().hasHeightForWidth())
        self.comp2_add_2.setSizePolicy(sizePolicy)
        self.comp2_add_2.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_add_2.setObjectName("comp2_add_2")
        self.add_score_layout.addWidget(self.comp2_add_2)
        self.comp2_add_3 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_add_3.sizePolicy().hasHeightForWidth())
        self.comp2_add_3.setSizePolicy(sizePolicy)
        self.comp2_add_3.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_add_3.setObjectName("comp2_add_3")
        self.add_score_layout.addWidget(self.comp2_add_3)
        self.comp2_add_4 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_add_4.sizePolicy().hasHeightForWidth())
        self.comp2_add_4.setSizePolicy(sizePolicy)
        self.comp2_add_4.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_add_4.setObjectName("comp2_add_4")
        self.add_score_layout.addWidget(self.comp2_add_4)
        self.comp2_add_a = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_add_a.sizePolicy().hasHeightForWidth())
        self.comp2_add_a.setSizePolicy(sizePolicy)
        self.comp2_add_a.setStyleSheet("background: rgb(255, 255, 130);\n"
"font: 20pt \'Arial\';\n"
"")
        self.comp2_add_a.setObjectName("comp2_add_a")
        self.add_score_layout.addWidget(self.comp2_add_a)
        self.comp2_add_p = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_add_p.sizePolicy().hasHeightForWidth())
        self.comp2_add_p.setSizePolicy(sizePolicy)
        self.comp2_add_p.setStyleSheet("background:rgb(200, 0, 0);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_add_p.setObjectName("comp2_add_p")
        self.add_score_layout.addWidget(self.comp2_add_p)
        self.verticalLayout.addLayout(self.add_score_layout)
        self.del_score_layout = QtWidgets.QHBoxLayout()
        self.del_score_layout.setObjectName("del_score_layout")
        self.comp1_del_2 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_del_2.sizePolicy().hasHeightForWidth())
        self.comp1_del_2.setSizePolicy(sizePolicy)
        self.comp1_del_2.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);\n"
"")
        self.comp1_del_2.setObjectName("comp1_del_2")
        self.del_score_layout.addWidget(self.comp1_del_2)
        self.comp1_del_3 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_del_3.sizePolicy().hasHeightForWidth())
        self.comp1_del_3.setSizePolicy(sizePolicy)
        self.comp1_del_3.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_del_3.setObjectName("comp1_del_3")
        self.del_score_layout.addWidget(self.comp1_del_3)
        self.comp1_del_4 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_del_4.sizePolicy().hasHeightForWidth())
        self.comp1_del_4.setSizePolicy(sizePolicy)
        self.comp1_del_4.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_del_4.setObjectName("comp1_del_4")
        self.del_score_layout.addWidget(self.comp1_del_4)
        self.comp1_del_a = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_del_a.sizePolicy().hasHeightForWidth())
        self.comp1_del_a.setSizePolicy(sizePolicy)
        self.comp1_del_a.setStyleSheet("background: rgb(255, 255, 130);\n"
"font: 20pt \'Arial\';\n"
"")
        self.comp1_del_a.setObjectName("comp1_del_a")
        self.del_score_layout.addWidget(self.comp1_del_a)
        self.comp1_del_p = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_del_p.sizePolicy().hasHeightForWidth())
        self.comp1_del_p.setSizePolicy(sizePolicy)
        self.comp1_del_p.setStyleSheet("background:rgb(200, 0, 0);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp1_del_p.setObjectName("comp1_del_p")
        self.del_score_layout.addWidget(self.comp1_del_p)
        self.stop_button = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon4)
        self.stop_button.setIconSize(QtCore.QSize(32, 32))
        self.stop_button.setObjectName("stop_button")
        self.del_score_layout.addWidget(self.stop_button)
        self.comp2_del_2 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_del_2.sizePolicy().hasHeightForWidth())
        self.comp2_del_2.setSizePolicy(sizePolicy)
        self.comp2_del_2.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_del_2.setObjectName("comp2_del_2")
        self.del_score_layout.addWidget(self.comp2_del_2)
        self.comp2_del_3 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_del_3.sizePolicy().hasHeightForWidth())
        self.comp2_del_3.setSizePolicy(sizePolicy)
        self.comp2_del_3.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_del_3.setObjectName("comp2_del_3")
        self.del_score_layout.addWidget(self.comp2_del_3)
        self.comp2_del_4 = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_del_4.sizePolicy().hasHeightForWidth())
        self.comp2_del_4.setSizePolicy(sizePolicy)
        self.comp2_del_4.setStyleSheet("background: rgb(125, 170, 125);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_del_4.setObjectName("comp2_del_4")
        self.del_score_layout.addWidget(self.comp2_del_4)
        self.comp2_del_a = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_del_a.sizePolicy().hasHeightForWidth())
        self.comp2_del_a.setSizePolicy(sizePolicy)
        self.comp2_del_a.setStyleSheet("background: rgb(255, 255, 130);\n"
"font: 20pt \'Arial\';\n"
"")
        self.comp2_del_a.setObjectName("comp2_del_a")
        self.del_score_layout.addWidget(self.comp2_del_a)
        self.comp2_del_p = QtWidgets.QPushButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_del_p.sizePolicy().hasHeightForWidth())
        self.comp2_del_p.setSizePolicy(sizePolicy)
        self.comp2_del_p.setStyleSheet("background:rgb(200, 0, 0);\n"
"font: 20pt \'Arial\';\n"
"color: rgb(255, 255, 255);")
        self.comp2_del_p.setObjectName("comp2_del_p")
        self.del_score_layout.addWidget(self.comp2_del_p)
        self.verticalLayout.addLayout(self.del_score_layout)
        Control.setCentralWidget(self.central_widget)

        self.retranslateUi(Control)
        self.division_combobox.setCurrentIndex(-1)
        self.comp2_flag_combobox.setCurrentIndex(-1)
        QtCore.QObject.connect(self.comp1_lineedit, QtCore.SIGNAL("textChanged(QString)"), self.comp1_name_label.setText)
        QtCore.QObject.connect(self.comp2_lineedit, QtCore.SIGNAL("textChanged(QString)"), self.comp2_name_label.setText)
        QtCore.QMetaObject.connectSlotsByName(Control)

    def retranslateUi(self, Control):
        Control.setWindowTitle(QtWidgets.QApplication.translate("Control", "Openroll", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Control", "Load Logo:", None, -1))
        self.load_logo_button.setText(QtWidgets.QApplication.translate("Control", "...", None, -1))
        self.division_label.setText(QtWidgets.QApplication.translate("Control", "Division: ", None, -1))
        self.buzzer_label.setText(QtWidgets.QApplication.translate("Control", "Buzzer Sound:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Control", "Points", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Control", "Advantages", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Control", "Penalties", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Control", "Points", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Control", "Advantages", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Control", "Penalties", None, -1))
        self.comp1_pts_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp1_adv_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp1_pen_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp2_pts_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp2_adv_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp2_pen_label.setText(QtWidgets.QApplication.translate("Control", "0", None, -1))
        self.comp1_name_label.setText(QtWidgets.QApplication.translate("Control", "Competitor A", None, -1))
        self.comp2_name_label.setText(QtWidgets.QApplication.translate("Control", "Competitor B", None, -1))
        self.comp1_lineedit.setText(QtWidgets.QApplication.translate("Control", "Competitor A", None, -1))
        self.p1_push_button.setText(QtWidgets.QApplication.translate("Control", "...", None, -1))
        self.timer_label.setText(QtWidgets.QApplication.translate("Control", "5:00", None, -1))
        self.comp2_lineedit.setText(QtWidgets.QApplication.translate("Control", "Competitor B", None, -1))
        self.p2_push_button.setText(QtWidgets.QApplication.translate("Control", "...", None, -1))
        self.comp1_add_2.setText(QtWidgets.QApplication.translate("Control", "+2", None, -1))
        self.comp1_add_3.setText(QtWidgets.QApplication.translate("Control", "+3", None, -1))
        self.comp1_add_4.setText(QtWidgets.QApplication.translate("Control", "+4", None, -1))
        self.comp1_add_a.setText(QtWidgets.QApplication.translate("Control", "+A", None, -1))
        self.comp1_add_p.setText(QtWidgets.QApplication.translate("Control", "+P", None, -1))
        self.comp2_add_2.setText(QtWidgets.QApplication.translate("Control", "+2", None, -1))
        self.comp2_add_3.setText(QtWidgets.QApplication.translate("Control", "+3", None, -1))
        self.comp2_add_4.setText(QtWidgets.QApplication.translate("Control", "+4", None, -1))
        self.comp2_add_a.setText(QtWidgets.QApplication.translate("Control", "+A", None, -1))
        self.comp2_add_p.setText(QtWidgets.QApplication.translate("Control", "+P", None, -1))
        self.comp1_del_2.setText(QtWidgets.QApplication.translate("Control", "-2", None, -1))
        self.comp1_del_3.setText(QtWidgets.QApplication.translate("Control", "-3", None, -1))
        self.comp1_del_4.setText(QtWidgets.QApplication.translate("Control", "-4", None, -1))
        self.comp1_del_a.setText(QtWidgets.QApplication.translate("Control", "-A", None, -1))
        self.comp1_del_p.setText(QtWidgets.QApplication.translate("Control", "-P", None, -1))
        self.comp2_del_2.setText(QtWidgets.QApplication.translate("Control", "-2", None, -1))
        self.comp2_del_3.setText(QtWidgets.QApplication.translate("Control", "-3", None, -1))
        self.comp2_del_4.setText(QtWidgets.QApplication.translate("Control", "-4", None, -1))
        self.comp2_del_a.setText(QtWidgets.QApplication.translate("Control", "-A", None, -1))
        self.comp2_del_p.setText(QtWidgets.QApplication.translate("Control", "-P", None, -1))

import openroll_rc
