# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scoreboard.ui',
# licensing of 'scoreboard.ui' applies.
#
# Created: Thu Jun 27 09:26:23 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Scoreboard(object):
    def setupUi(self, Scoreboard):
        Scoreboard.setObjectName("Scoreboard")
        Scoreboard.resize(1600, 830)
        Scoreboard.setMinimumSize(QtCore.QSize(1600, 830))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Scoreboard.setWindowIcon(icon)
        self.main_vlayout = QtWidgets.QVBoxLayout(Scoreboard)
        self.main_vlayout.setObjectName("main_vlayout")
        self.comp1_layout = QtWidgets.QHBoxLayout()
        self.comp1_layout.setObjectName("comp1_layout")
        self.comp1_name = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_name.sizePolicy().hasHeightForWidth())
        self.comp1_name.setSizePolicy(sizePolicy)
        self.comp1_name.setStyleSheet("font: 36pt \'Arial\';\n"
"background-color: rgb(0, 0, 200);\n"
"color: \'white\';")
        self.comp1_name.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_name.setObjectName("comp1_name")
        self.comp1_layout.addWidget(self.comp1_name)
        self.comp1_points = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_points.sizePolicy().hasHeightForWidth())
        self.comp1_points.setSizePolicy(sizePolicy)
        self.comp1_points.setMinimumSize(QtCore.QSize(288, 247))
        self.comp1_points.setAutoFillBackground(False)
        self.comp1_points.setStyleSheet("background-color: rgb(60, 125, 60);\n"
"color: \'white\';\n"
"font: 192pt \"Arial\";\n"
"")
        self.comp1_points.setFrameShape(QtWidgets.QFrame.Box)
        self.comp1_points.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.comp1_points.setTextFormat(QtCore.Qt.AutoText)
        self.comp1_points.setScaledContents(False)
        self.comp1_points.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_points.setObjectName("comp1_points")
        self.comp1_layout.addWidget(self.comp1_points)
        self.comp1_advantages = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_advantages.sizePolicy().hasHeightForWidth())
        self.comp1_advantages.setSizePolicy(sizePolicy)
        self.comp1_advantages.setMinimumSize(QtCore.QSize(288, 247))
        self.comp1_advantages.setStyleSheet("font: 192pt \'Arial\';\n"
"background-color: rgb(225, 225, 0);\n"
"color: \'white\';")
        self.comp1_advantages.setFrameShape(QtWidgets.QFrame.Box)
        self.comp1_advantages.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.comp1_advantages.setTextFormat(QtCore.Qt.AutoText)
        self.comp1_advantages.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_advantages.setObjectName("comp1_advantages")
        self.comp1_layout.addWidget(self.comp1_advantages)
        self.comp1_penalties = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp1_penalties.sizePolicy().hasHeightForWidth())
        self.comp1_penalties.setSizePolicy(sizePolicy)
        self.comp1_penalties.setMinimumSize(QtCore.QSize(288, 247))
        self.comp1_penalties.setStyleSheet("font: 192pt \'Arial\';\n"
"background-color: rgb(200,0,0);\n"
"color: \'white\';")
        self.comp1_penalties.setFrameShape(QtWidgets.QFrame.Box)
        self.comp1_penalties.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.comp1_penalties.setTextFormat(QtCore.Qt.AutoText)
        self.comp1_penalties.setAlignment(QtCore.Qt.AlignCenter)
        self.comp1_penalties.setMargin(0)
        self.comp1_penalties.setObjectName("comp1_penalties")
        self.comp1_layout.addWidget(self.comp1_penalties)
        self.main_vlayout.addLayout(self.comp1_layout)
        self.comp2_layout = QtWidgets.QHBoxLayout()
        self.comp2_layout.setObjectName("comp2_layout")
        self.comp2_name = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_name.sizePolicy().hasHeightForWidth())
        self.comp2_name.setSizePolicy(sizePolicy)
        self.comp2_name.setStyleSheet("font: 36pt \'Arial\';\n"
"background-color: \'white\';")
        self.comp2_name.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_name.setObjectName("comp2_name")
        self.comp2_layout.addWidget(self.comp2_name)
        self.comp2_points = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_points.sizePolicy().hasHeightForWidth())
        self.comp2_points.setSizePolicy(sizePolicy)
        self.comp2_points.setMinimumSize(QtCore.QSize(288, 247))
        self.comp2_points.setStyleSheet("font: 192pt \'Arial\';\n"
"background-color: rgb(60, 125, 60);\n"
"color: \'white\';")
        self.comp2_points.setFrameShape(QtWidgets.QFrame.Box)
        self.comp2_points.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.comp2_points.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_points.setObjectName("comp2_points")
        self.comp2_layout.addWidget(self.comp2_points)
        self.comp2_advantages = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_advantages.sizePolicy().hasHeightForWidth())
        self.comp2_advantages.setSizePolicy(sizePolicy)
        self.comp2_advantages.setMinimumSize(QtCore.QSize(288, 247))
        self.comp2_advantages.setStyleSheet("font: 192pt \'Arial\';\n"
"background-color: rgb(225, 225, 0);\n"
"color: \'white\';")
        self.comp2_advantages.setFrameShape(QtWidgets.QFrame.Box)
        self.comp2_advantages.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.comp2_advantages.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_advantages.setObjectName("comp2_advantages")
        self.comp2_layout.addWidget(self.comp2_advantages)
        self.comp2_penalties = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comp2_penalties.sizePolicy().hasHeightForWidth())
        self.comp2_penalties.setSizePolicy(sizePolicy)
        self.comp2_penalties.setMinimumSize(QtCore.QSize(288, 247))
        self.comp2_penalties.setStyleSheet("font: 192pt \'Arial\';\n"
"background-color: rgb(200, 0, 0);\n"
"color: \'white\';")
        self.comp2_penalties.setFrameShape(QtWidgets.QFrame.Box)
        self.comp2_penalties.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.comp2_penalties.setAlignment(QtCore.Qt.AlignCenter)
        self.comp2_penalties.setObjectName("comp2_penalties")
        self.comp2_layout.addWidget(self.comp2_penalties)
        self.main_vlayout.addLayout(self.comp2_layout)
        self.timer_layout = QtWidgets.QHBoxLayout()
        self.timer_layout.setObjectName("timer_layout")
        self.user_logo = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.user_logo.sizePolicy().hasHeightForWidth())
        self.user_logo.setSizePolicy(sizePolicy)
        self.user_logo.setMinimumSize(QtCore.QSize(50, 50))
        self.user_logo.setMaximumSize(QtCore.QSize(256, 256))
        self.user_logo.setText("")
        self.user_logo.setPixmap(QtGui.QPixmap(":/icons/openroll.png"))
        self.user_logo.setScaledContents(True)
        self.user_logo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_logo.setObjectName("user_logo")
        self.timer_layout.addWidget(self.user_logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.timer_layout.addItem(spacerItem)
        self.timer_display = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.timer_display.sizePolicy().hasHeightForWidth())
        self.timer_display.setSizePolicy(sizePolicy)
        self.timer_display.setStyleSheet("font: 192pt \'Consolas\';")
        self.timer_display.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_display.setObjectName("timer_display")
        self.timer_layout.addWidget(self.timer_display)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.timer_layout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.divisionLabel = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.divisionLabel.sizePolicy().hasHeightForWidth())
        self.divisionLabel.setSizePolicy(sizePolicy)
        self.divisionLabel.setStyleSheet("font: 24pt \'Arial\';\n"
"")
        self.divisionLabel.setScaledContents(False)
        self.divisionLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.divisionLabel.setIndent(-1)
        self.divisionLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.divisionLabel.setObjectName("divisionLabel")
        self.verticalLayout.addWidget(self.divisionLabel)
        self.beltLabel = QtWidgets.QLabel(Scoreboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.beltLabel.sizePolicy().hasHeightForWidth())
        self.beltLabel.setSizePolicy(sizePolicy)
        self.beltLabel.setStyleSheet("font:  24pt \'Arial\';\n"
"")
        self.beltLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.beltLabel.setObjectName("beltLabel")
        self.verticalLayout.addWidget(self.beltLabel)
        self.timer_layout.addLayout(self.verticalLayout)
        self.main_vlayout.addLayout(self.timer_layout)

        self.retranslateUi(Scoreboard)
        QtCore.QMetaObject.connectSlotsByName(Scoreboard)

    def retranslateUi(self, Scoreboard):
        Scoreboard.setWindowTitle(QtWidgets.QApplication.translate("Scoreboard", "Openroll", None, -1))
        self.comp1_name.setText(QtWidgets.QApplication.translate("Scoreboard", "Competitor 1", None, -1))
        self.comp1_points.setText(QtWidgets.QApplication.translate("Scoreboard", "0", None, -1))
        self.comp1_advantages.setText(QtWidgets.QApplication.translate("Scoreboard", "0", None, -1))
        self.comp1_penalties.setText(QtWidgets.QApplication.translate("Scoreboard", "0", None, -1))
        self.comp2_name.setText(QtWidgets.QApplication.translate("Scoreboard", "Competitor 2", None, -1))
        self.comp2_points.setText(QtWidgets.QApplication.translate("Scoreboard", "0", None, -1))
        self.comp2_advantages.setText(QtWidgets.QApplication.translate("Scoreboard", "0", None, -1))
        self.comp2_penalties.setText(QtWidgets.QApplication.translate("Scoreboard", "0", None, -1))
        self.timer_display.setText(QtWidgets.QApplication.translate("Scoreboard", "5:00", None, -1))
        self.divisionLabel.setText(QtWidgets.QApplication.translate("Scoreboard", "<html><head/><body><p><span style=\" font-size:18pt;\">ADULT - AGE 18-29</span></p></body></html>", None, -1))
        self.beltLabel.setText(QtWidgets.QApplication.translate("Scoreboard", "<html><head/><body><p><span style=\" font-size:18pt;\">WHITE</span></p></body></html>", None, -1))

import openroll_rc
